/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   fabric-location.js
 *   fabric-location.js
 */

/// <reference path="location-mixin.d.ts" />

/**
 * `fabric-location`
 */
declare class FabricLocation extends
  Fabric.LocationMixin(
  Polymer.Element) {
}

interface HTMLElementTagNameMap {
  "fabric-location": FabricLocation;
  "fabric-location": FabricLocation;
}

/**
 * `fabric-location`
 */
declare class FabricLocation extends
  Fabric.LocationMixin(
  Polymer.Element) {
}
